# Generated by https://quicktype.io

from typing import List, Optional


class Ad:
    name: str
    company: str
    spec: str
    price: int
    types: List[str]
    tags: List[str]
    desc: str

    def __init__(self, name: str, company: str, spec: str, price: int, types: List[str], tags: List[str], desc: str) -> None:
        self.name = name
        self.company = company
        self.spec = spec
        self.price = price
        self.types = types
        self.tags = tags
        self.desc = desc


class Station:
    name: str
    ads: Optional[List[Ad]]

    def __init__(self, name: str, ads: Optional[List[Ad]]) -> None:
        self.name = name
        self.ads = ads


class Subway:
    line: int
    stations: List[Station]

    def __init__(self, line: int, stations: List[Station]) -> None:
        self.line = line
        self.stations = stations


class SubwayList:
    lines: List[Subway]

    def __init__(self, lines: List[Subway]) -> None:
        self.lines = lines
